const skillGroups: [string, string[]][] = [
  ["Paid Media", ["Taboola", "Meta Ads", "native", "CPA/CPL"]],
  ["Tracking & Attribution", ["S2S postbacks", "RedTrack", "Voluum", "Skro"]],
  ["Affiliate Platforms", ["CAKE", "Impact", "Affise", "Everflow", "TUNE", "FlexOffers"]],
  ["Build", ["Next.js", "TypeScript", "PostgreSQL/Supabase", "technical SEO", "Salesforce", "advanced Excel"]],
];

const chapters = [
  { number: "01", date: "2023 -> now", title: "Scaling offers at Digital Concept", text: "I brought new approaches to scaling CPA/CPL offers across Taboola and Facebook (Meta) Ads. Creative and audience testing, landing-page iteration, and disciplined spend reallocation generated over $100,000 USD in profit within a six-month span.", proof: ["Run the attribution layer myself: S2S postbacks, RedTrack, Voluum and Skro", "Operate across CAKE, Impact, Affise, Everflow, TUNE and FlexOffers", "Connect acquisition decisions to clean conversion and payout data"] },
  { number: "02", date: "Owner-operator", title: "Building and monetizing TheChoiceQuotes", text: "I built the personal-finance comparison site myself and pioneered hosting platform offers directly on the site, leveraging Google search traffic. It is the full loop of content, technical SEO and affiliate monetization.", proof: ["Own the content and affiliate monetization workflow", "Handle indexing, canonicalization and .htaccess implementation", "Visit thechoicequotes.com"] },
  { number: "03", date: "Idea -> shipped", title: "Product & software journey", text: "I built my own infrastructure to understand products from the inside. Most visibly, Celeray is a live payments-integrated community rewards app, showing I can take a product from idea to shipped, including payment debugging in production.", proof: ["Next.js, TypeScript, Supabase and Paystack", "Real-time features and AI integrations", "Shipped product workflows, permissions and payment debugging"] },
  { number: "04", date: "Professional formation", title: "Where leadership was forged", text: "Multi-year leadership roles in a large structured organization taught me how organizations actually operate: program planning and execution, budgeting, coordination and formal reporting to senior leadership.", proof: ["Program planning and execution for 170+ participants", "Budgeting and financial reporting across multi-million-naira programs", "Coordinated volunteer and facilitator teams"] },
];

export default function Home() {
  return <>
    <nav><div className="wrap nav-inner"><a className="nav-name" href="#top">samuel.richard</a><div className="nav-links"><a href="#work">Work</a><a href="#journey">Journey</a><a href="#skills">Skills</a><a href="#about">About</a><a href="#contact">Contact</a></div></div></nav>

    <header className="hero wrap" id="top"><p className="hero-eyebrow">Samuel Richard - Lagos, Nigeria - Affiliate &amp; Performance Marketing</p><h1>I run the campaigns <span className="accent">and build the pipes.</span></h1><p className="hero-sub">Performance marketing and business development professional in Lagos with 4 years across paid acquisition, affiliate operations and tracking infrastructure. I work across Meta Ads, Taboola native, CPA/CPL economics, S2S postbacks, RedTrack, Voluum and network-side operations.</p><div className="postback" aria-label="Example server-to-server postback request"><span className="dim">$</span> GET https://track.samuelr.dev/postback <span className="org">?clickid=</span>{"{clickid}"}<span className="org">&amp;payout=</span>{"{payout}"}<span className="org">&amp;status=</span>approved<br /><span className="dim">-&gt; 200 OK</span>&nbsp;&nbsp;<span className="grn">conversion recorded - attribution intact</span><span className="cursor" aria-hidden="true" /></div><div className="hero-ctas"><a className="btn primary" href="#work">See the proof</a><a className="btn ghost" href="mailto:samuelrichards1844@gmail.com">Email me</a></div></header>

    <section id="work"><div className="wrap"><div className="sec-head"><h2>Proof of work</h2><span className="path">/selected-work - current systems and outcomes</span></div><article className="case"><div className="case-top"><div><h3>Paid traffic, attribution, and the full loop</h3><p className="role">Digital Concept - CPA/CPL acquisition - Taboola - Meta Ads</p></div><span className="chip ok">Profit generated</span></div><p>At Digital Concept, I scale offers through creative and audience testing, landing-page iteration, and spend reallocation. The result: over $100,000 USD in profit within a six-month span.</p><p>I also run the attribution layer myself, connecting campaign decisions to reliable conversion and payout data across multiple tracking and affiliate platforms.</p><div className="case-meta"><div className="kv"><div className="k">Outcome</div><div className="v">$100,000+ profit in six months</div></div><div className="kv"><div className="k">Acquisition</div><div className="v">Taboola native and Meta Ads</div></div><div className="kv"><div className="k">Attribution</div><div className="v">S2S postbacks and tracker operations</div></div></div></article><article className="case"><div className="case-top"><div><h3>Celeray - payments-integrated community rewards app</h3><p className="role">Next.js - TypeScript - Supabase - Paystack - real-time features - AI integrations</p></div><span className="chip ok">Live product</span></div><p>Celeray shows the product and engineering capability I built by creating my own infrastructure. I took it from idea to shipped, including payment debugging in production.</p><div className="case-meta"><div className="kv"><div className="k">Product</div><div className="v">Community rewards and payments</div></div><div className="kv"><div className="k">Stack</div><div className="v">Next.js, TypeScript, Supabase</div></div><div className="kv"><div className="k">Payments</div><div className="v">Paystack integration</div></div></div></article><article className="case"><div className="case-top"><div><h3>TheChoiceQuotes - content to traffic to conversion</h3><p className="role">Owner-operator - thechoicequotes.com - technical SEO and affiliate monetization</p></div><span className="chip ok">Live - monetized</span></div><p>I built the personal-finance comparison site myself and pioneered hosting platform offers directly on the site, leveraging Google search traffic.</p><p>The work spans content, indexing, canonicalization, .htaccess implementation, and affiliate monetization.</p><div className="case-links"><a href="https://thechoicequotes.com" target="_blank" rel="noopener noreferrer">Visit the site -&gt;</a></div></article></div></section>

    <section id="journey"><div className="wrap"><div className="sec-head"><h2>The Journey</h2><span className="path">/narrative - four chapters</span></div><div className="xp">{chapters.map((chapter) => <article className="xp-item" key={chapter.number}><h3>{chapter.number} - {chapter.title}</h3><p className="where">{chapter.date}</p><p>{chapter.text}</p><ul>{chapter.proof.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>

    <section id="skills"><div className="wrap"><div className="sec-head"><h2>What I work with</h2><span className="path">/toolkit - no proficiency labels</span></div><div className="skills-grid">{skillGroups.map(([title, skills]) => <div className="skill-card" key={title}><h3>{title}</h3><ul>{skills.map((skill) => <li key={skill}>{skill}</li>)}</ul></div>)}</div></div></section>

    <section id="about"><div className="wrap"><div className="sec-head"><h2>About</h2><span className="path">/context - Lagos, Nigeria</span></div><article className="case"><p>I&apos;m Lagos-based with a B.Eng. in Electronics Engineering and a business development background at Digital Concept and previously Jumia. I&apos;m equally at home negotiating a CPA deal and debugging the postback behind it.</p></article></div></section>

    <section id="leadership"><div className="wrap"><div className="sec-head"><h2>Leadership formation</h2><span className="path">/professional-formation - structured organizations</span></div><div className="lead-grid"><div className="lead-card"><div className="num">170+</div><div className="what">Participants supported</div><p>Program planning and execution involving large participant groups.</p></div><div className="lead-card"><div className="num">Multi-million</div><div className="what">Naira budgets</div><p>Budgeting and financial reporting for structured programs.</p></div><div className="lead-card"><div className="num">Teams</div><div className="what">Volunteers and facilitators</div><p>Coordinated people, schedules and delivery across programs.</p></div><div className="lead-card"><div className="num">Formal</div><div className="what">Senior reporting</div><p>Clear reporting and accountability to senior leadership.</p></div></div></div></section>

    <footer id="contact"><div className="wrap"><h2>Hiring for affiliate, performance, or ad-tech roles? Let&apos;s talk.</h2><div className="foot-links"><a className="btn primary" href="mailto:samuelrichards1844@gmail.com">samuelrichards1844@gmail.com</a><a className="btn ghost" href="https://linkedin.com/in/samuel-richard-257418220" target="_blank" rel="noopener noreferrer">LinkedIn -&gt;</a></div><p className="foot-note">Designed and built by Samuel Richard with Next.js. <a href="https://github.com/Richards28910/portfolio" target="_blank" rel="noopener noreferrer">View source on GitHub -&gt;</a></p></div></footer>
  </>;
}
